version: '3'
services:
    app:
        container_name: Apache_julienduranleau.com
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: simplewebhost
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
        links:
            - mysql
